accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='user_register'),
    path('verify/',views.UserRegisterVerifyCodeView.as_view(),name='verify_code'),
    path('login/',views.UserLoginView.as_view(),name='user_login'),
    path('logout/',views.UserLogoutView.as_view(),name='user_logout'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('category/<slug:category_slug>/',views.HomeView.as_view(),name='category_filter'),
    path('<slug:slug>/',views.ProductDetailView.as_view(),name='product_detail'),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
          <div class="navbar-nav">
              <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
              {% if request.user.is_authenticated %}
              <a class="nav-link active" href="{% url 'accounts:user_logout' %}">Logout</a>
              {% else %}
              <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
              <a class="nav-link active" href="{% url 'accounts:user_login' %}">Login</a>
              {% endif %}
          </div>    
      </div>
</nav>